<script src="controller/user_terms.js"></script>
<!-- Modal -->
  <div class="modal fade" id="user_terms" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true" style="left:-450px;">
    <div class="modal-dialog">
      <div class="modal-content" style="width:1024px;">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Convenio de Políticas de Privacidad y Condiciones de Uso de Plataforma Web Eollice</h4>
        </div>
        <div class="modal-body" id="userterms_body">
<p><b>Introducción</b><br>
El presente Convenio busca regular la relación entre usuarios (o “inversionistas”) y entre inversionistas y la Plataforma Eollice (o “Plataforma” o “la Plataforma”), además de presentar las Políticas de Privacidad en cuanto al uso de información de los inversionistas, recomendaciones de privacidad y sugeridas al inversionista.<br>
</p><br>
<p><b>1. Propiedad Intelectual de Plataforma</b><br></p>
<p><b>Contenidos protegidos.</b><br>
Todo el material de Plataforma y sus Contenidos incluyendo, a modo de ejemplo y no limitativo, los textos, datos, artículos, diseños, logotipos, marcas registradas, formularios, documentos, gráficos, fotos, imágenes, contenidos en general, su organización y compilación, códigos fuente, software, entre otros, y cualquier otra información contenida en la plataforma es de propiedad de Eollice y se encuentra protegido por las normas de propiedad intelectual y por los tratados internacionales vigentes en Chile en esta materia. El Inversionista comprende y acepta que el contenido es de propiedad de Eollice.
</p><p><b>Marcas Registradas.</b>
<br>Eollice (incluyendo su logo y todos los logos derivados del logo de Eollice), su marca, nombres comerciales o signos distintivos que aparecen en la Plataforma, así como los dominios www.eollice.com y www.eollice.cl, son marcas registradas de propiedad de Eollice. El Inversionista reconoce, declara y acepta que el uso de Plataforma y a los servicios prestados por Eollice no le otorga derecho alguno sobre las Marcas Registradas ni sobre los Contenidos.
</p><p><b>Prohibiciones.</b>
<ol>
  <li>El Contenido no podrá ser copiado, modificado, reproducido, reutilizado, redistribuido, republicado, expuesto o posteado por el Inversionista en ninguna forma y bajo ningún medio, incluyendo a modo de ejemplo y no limitativo, medios electrónicos, mecánicos, grabaciones, fotocopias, entre otros, sin la previa autorización escrita por parte de Eollice.</li>
  <li>Nada en la Plataforma podrá ser utilizado por terceros sin la previa autorización escrita de Eollice y para cada vez que se requieran.</li>
  <li>El acceso, descarga, transmisión e impresión de cualquier Contenido puede ser realizado por el inversionista exclusivamente para fines de uso personal y sólo en relación y en función a un correcto uso para el Inversionista de los servicios que le provee Eollice a través de Plataforma.</li>
  <li>El Inversionista no podrá modificar o realizar creaciones a partir de parte de los Contenidos o de la totalidad de estos, que se encuentren publicados en la Plataforma.</li>
  <li>Se prohíbe el uso del Contenido de Plataforma en cualquier otro sitio, incluyendo links de Eollice en otros sitios web, con o sin el logo de Eollice, sin la previa autorización escrita por parte de Eollice.</li>
  <li>El Inversionista no podrá reproducir un sitio “espejo” de Plataforma web de Eollice o de parte de éste, mantenerlo en otros servidores ni publicarlos en Internet.</li>
</ol></p>
<p><b>Consecuencias del uso sin consentimiento de Eollice.</b><br>
Cualquier uso no autorizado de cualquier Contenido de Plataforma de acuerdo a esta cláusula, constituirá una violación de las leyes y regulaciones en las materias de derechos de autor y de propiedad intelectual y dará derecho a Eollice para desactivar la cuenta y registro del inversionista, pudiendo poner término al presente Convenio de uso de Plataforma, al servicio asociado al mismo y negar el acceso al Inversionista. Lo anterior, es sin perjuicio del derecho de Eollice de ejercer todas las acciones, tanto civiles como penales, destinadas al resguardo de sus legítimos derechos de propiedad intelectual. Cualquier pregunta relativa a las marcas registradas y/o al uso del Contenido de Eollice deberá ser realizada directamente a Eollice.
</p><br><p><b>2. Uso aceptable de Plataforma y su contenido</b></p>
<p><b>Generales.</b>
El Inversionista acepta usar el contenido y la plataforma sólo con propósitos que caen dentro del marco legal y regulatorio, de acuerdo a la moral y buenas costumbres, en conformidad al orden público y según los términos y condiciones del presente Convenio de Uso de Plataforma.
Eollice no asegura que los Contenidos de Plataforma y los servicios prestados a través del mismo son apropiados fuera de Chile. Por lo tanto, si el Inversionista accede a la plataforma desde fuera de Chile, el inversionista comprende y acepta que el acceso y uso de Plataforma es bajo su responsabilidad y éste debe asegurarse de cumplir con las leyes y normas específicas de su jurisdicción.
</p><b>Prohibiciones.</b><br>
El Inversionista comprende y acepta que además de las prohibiciones establecidas en otras secciones de este Convenio de Uso de Plataforma, existen prohibiciones específicas en cuanto al uso de Plataforma y de sus Contenidos, por tanto el Inversionista no podrá:
<ol>
  <li>Usar la Plataforma y/o el Contenido del mismo para fines que violen las leyes y regulaciones vigentes en Chile y acuerdos internacionales, ni incurrir en cualquier práctica que de cualquier manera pudiere atentar contra la ley, la moral y las buenas costumbres o que viole los derechos de cualquier inversionista y/o de Eollice;</li>
  <li>Distribuir desde la Plataforma información o contenidos que pudieren ser de carácter fraudulento, engañoso (incluyendo publicidad engañosa de otros productos o servicios ajenos a Eollice), discriminatorio, violento, amenazante, de acoso, difamatorio, denigratorio, inmoral, obsceno o pornográfico y que pudiere por dicha condición dañar a terceros y/o a Eollice;</li>
  <li>Distribuir desde Plataforma sin la previa autorización del titular información o contenidos que se encuentren protegidos por las leyes de propiedad intelectual y que con dicha acción se afecte a terceros y/o a Eollice;</li>
  <li>Usar y/o hackear la Plataforma de cualquier forma que pudiere dañar, inutilizar, deteriorar, afectar o sobrecargar la normal utilización de Plataforma, de sus servicios y/o que pudiere afectar los sistemas, plataformas, softwares y hardwares de Eollice;</li>
  <li>Transmitir o distribuir en la plataforma cualquier virus, programa o elemento electrónico que pudiere dañar o impedir el normal funcionamiento de Plataforma, los sistemas de Eollice, sus equipos informáticos, y a su vez, interferir con su seguridad, generando un daño a Eollice y a terceros;</li>
  <li>Impedir o interrumpir el uso de Plataforma a terceros;</li>
  <li>Efectuar un mal uso de contraseñas, ya sea la propia como las de terceros, así como usar cuentas y/o información personal de terceros, sin contar con la autorización del tercero titular;</li>
  <li>Monitorear, copiar o extraer información de Plataforma, ya sea utilizando procesos automáticos o manuales;</li>
  <li>Subir, publicar, postear, transmitir, compartir, guardar o hacer pública en la Plataforma o en cualquier otro sitio web, cualquier información privada o de identificación personal de cualquier Miembro de Eollice, incluyendo a modo de ejemplo y no limitativo la publicación de nombres, direcciones, números de teléfono, direcciones de correo electrónico, direcciones particulares o laborales, R.U.T., información de cuentas corrientes y/o de tarjetas de crédito, entre otras, independiente de que esa información privada o de identificación personal de un tercero se encuentre publicada deliberada o accidentalmente en Eollice de modo visible para los Miembros;</li>
  <li>Transmitir la información personal mencionada en el punto anterior a través de emails, blogs, foros o cualquier otro medio de comunicación de cualquier tipo;</li>
  <li>Efectuar un mal uso de cualquier información y contenido accesibles desde la Plataforma, entendiendo el mal uso – a modo de ejemplo y no limitativo – como las acciones que pudieren menoscabar los derechos fundamentales y las libertades reconocidas constitucionalmente; las acciones que induzcan o promuevan acciones delictivas; las acciones que induzcan a estados de ansiedad y temor a terceros; entre otras.</li>
</ol>
La infracción de cualquiera de las disposiciones de esta cláusula séptima, dará derecho a Eollice para desactivar la cuenta y Registro del Inversionista, pudiendo poner término al presente Convenio de Uso de Plataforma, al servicio asociado al mismo y negar el acceso al Inversionista. Lo anterior, es sin perjuicio del derecho de Eollice de ejercer todas las acciones, tanto civiles como penales, destinadas al resguardo de sus legítimos derechos y las de sus Miembros e Inversionistas.
</p><p><b>Políticas de protección de información, confidencialidad y privacidad</b><br>
Esta política revela qué información recogemos y cómo la utilizamos, así como las opciones que usted puede hacer sobre la manera en que su información es recogida y usada. También explicamos cómo se usará la información personal o de identificación personal que podemos solicitar, estas explicaciones se pueden encontrar en las mismas páginas en las que se solicita la información. También el detalle nuestra política de seguridad, que describe cómo se protege su información personal.
En general, recopilamos varios tipos de información de usted:
<ol>
  <li>Los datos personales necesarios para verificar su identidad.</li>
  <li>Datos personales y económicos necesarios para invertir en la plataforma Eollice.</li>
  <li>Información acerca de sus visitas y uso de este sitio web para ayudar a mantener las características apropiadas, funcionalidad y experiencia del inversionista</li>
</ol>
El Inversionista se obliga a guardar reserva sobre los datos proporcionados por otros Inversionistas, con especial énfasis en la información de aquellos Inversionistas que expresamente hayan solicitado tratarla con reserva.
El Inversionista se obliga a custodiar su Nombre de Inversionista y Contraseña, los cuales son de su responsabilidad y uso exclusivo, debiendo realizar un correcto uso de las mismas. En consecuencia, Eollice no se hace responsable de los daños generados al Inversionista por mal uso de terceros del Nombre de Inversionista y Contraseña. En caso de detectar mal uso de su Nombre de Inversionista o Contraseña, el Inversionista se obliga a dar aviso inmediato a Eollice, mediante correo electrónico dirigido a contacto@eollice.com.
Eollice establece las Políticas de Privacidad de Plataforma, las cuales se encuentran disponibles en www.eollice.com. El Inversionista se obliga a leer y aceptar dichas políticas para poder navegar en la Plataforma y utilizar los servicios que ahí se ofrecen.
</p><br><p><b>3. Veracidad de la información del Inversionista</b>
</p><p><b>Responsabilidad del inversionista.</b><br> 
El Inversionista se obliga a que toda la información que proporcione a Eollice, ya sea a través de Plataforma (en formularios de Registro de Inversionista u otro medio suministrado por Eollice), y/o de otros medios que Eollice haya definido con el Inversionista (email, correo, telefónicamente, entre otros), debe ser veraz, fidedigna y comprobable. Asimismo, el Inversionista es responsable exclusivo de mantener su información personal siempre actualizada.
El Inversionista, a través de la aceptación de este Convenio, garantiza la autenticidad de todos aquellos datos proporcionados a Eollice y de aquellos datos que vaya actualizando en el tiempo, siendo el Inversionista el único responsable por los daños y perjuicios generados por cualquier inexactitud en la información que pudieran recaer sobre sí mismo, sobre Eollice y/o sobre terceros. Eollice no se hace responsable por las faltas en que incurra el Inversionista respecto de ésta clausula.
</p><p><b>Prohibiciones.</b><br> 
El Inversionista comprende que no podrá crear cuentas o utilizar la Plataforma proporcionando datos falsos.
</p><p><b>Requisitos para ser inversionista registrado en la Plataforma</b><br>
Para poder acceder a ser Inversionista Registrado de Eollice, el Inversionista debe contar con cédula nacional de identidad (RUT) y ser mayor de 18 años de edad.
</p><p><b>Verificaciones.</b><br> 
Eollice se reserva el derecho de verificar la información proporcionada por el Inversionista. En caso de comprobar que la información o una parte de ella no es veraz o no corresponde al Inversionista que la proporcionó, Eollice podrá desactivar la Cuenta y Registro del Inversionista, pudiendo poner término al presente Convenio de Uso de Plataforma, al servicio asociado al mismo, y negar el acceso al Inversionista. Lo anterior, es sin perjuicio del derecho de Eollice de iniciar las acciones legales que estime convenientes contra el Inversionista que haya proporcionado información falsa.
</p><p><b>Visualización y modificación de la información personal del inversionista</b><br>
Usted puede acceder y revisar la información personal que envíe en cualquier momento. Para actualizar la información de su perfil personal, puede acceder a su cuenta utilizando su dirección de correo electrónico y la contraseña especificada en el momento de la inscripción. Haga clic en la sección "Configuración" de la sección "Mi Cuenta" y realizar cambios en tu perfil si es necesario.
</p><p><b>Sobre compartir su información personal con terceros</b><br>
Trabajamos con una serie de socios confiables que realizan funciones vitales como parte de nuestras operaciones, incluyendo las agencias de crédito, bancos, agencias de cobro y los proveedores de servicios de pago electrónicos. La información se comparte con estas terceras partes sólo en la medida necesaria para que podamos procesar las transacciones que se inician o realizan otros servicios específicos, como colecciones. Nuestros socios están obligados por ley a mantener su información privada y segura.
Si utiliza nuestro blog en este sitio, debe tener en cuenta que cualquier información personal que usted envíe puede ser leída, recopilada o utilizada por otros inversionistas de este foro, y podría ser utilizado para enviar mensajes no solicitados. No somos responsables de la información que puede ser identificada personalmente que usted decida publicar en este foro.
Podemos compartir su información con carabineros u otras agencias gubernamentales como lo requiere la ley o con el propósito de limitar el fraude. Nos reservamos el derecho de revelar su información de identificación personal cuando creemos que la divulgación es necesaria para proteger nuestros derechos o para cumplir con un procedimiento judicial, orden judicial o proceso legal.
Nosotros no vendemos, arrendamos ni regalamos su información personal a terceros con fines de marketing ni sin fines de lucro.
</p><p><b>Política de Seguridad</b><br>
Estamos comprometidos a mantener la seguridad y confidencialidad de su información personal y financiera. Mantenemos medidas de seguridad física, electrónica y de procedimiento que cumplen o superan los estándares de la industria para las instituciones financieras.
Nosotros protegemos su información de cuenta confidencial almacenándolo en forma cifrada en los equipos que no están conectados a Internet. Tenemos el control de acceso a esta información a través de páginas web seguras y limitar el acceso a los empleados y terceras partes. No se permite la visibilidad de la información de cuenta bancaria o de tarjeta de crédito a través de la página web.
Contamos con firewalls y otras tecnologías de seguridad para proteger los servidores de ataques externos. Permitimos a nuestros servidores con la tecnología Secure Socket Layer (SSL) para establecer una conexión segura entre su computadora y nuestros servidores, la creación de una "conversación" privada que no se puede ver o acceder desde otras partes. Probamos nuestros sistemas de forma regular para garantizar que nuestros mecanismos de seguridad están al día.
También empleamos fin de apertura de sesión por inactividad para proteger su cuenta. Se le desconectará de la página de forma automática después de un período determinado de inactividad. Esta función de tiempo de espera se reduce el riesgo de que otros son capaces de acceder a su cuenta si deja su ordenador sin supervisión.
Cuando nos comuniquemos con usted acerca de su cuenta para confirmar una transferencia de fondos, es sólo de referencia los últimos cuatro dígitos de su número de cuenta bancaria, lo que se hace para su protección, de manera que pueda reconocer el origen o el destino cuenta como uno de su propiedad.
Las regulaciones estatales pueden requerir que mantenemos y reportamos información demográfica sobre los miembros que participan en las transacciones. También podemos mantener la información, incluyendo la información personal identificable de nuestros miembros.
</p><p><b>Política ANTISPAM</b><br>
El Inversionista se obliga a abstenerse de:
<ol>
  <li>Recopilar desde Plataforma datos con finalidad publicitaria;</li>
  <li>Transmitir, subir, postear, enviar por email o poner disponible cualquier material promocional o publicitario y/o cualquier tipo de comunicación con fines de venta u otros fines comerciales, que no fue solicitado y que no cuenta con la previa autorización de los terceros afectados;</li>
  <li>Transmitir desde Plataforma SPAM, cadenas de mensajes, correo basura o cualquier otro tipo de mensaje interno y/o correo electrónico masivo no solicitado;</li>
  <li>Hackear los sistemas de la Plataforma para acceder a sus bases de datos y obtener listas de distribución de emails, para luego realizar las acciones descritas en los puntos anteriores y/o para poner estas listas de distribución a disposición de terceros a través de la cesión o venta de las mismas.</li>
</ol>
</p><p><b>Vínculos a otros sitios web desde la Plataforma</b><br>
La Plataforma podrá contener vínculos a otros sitios web de propiedad, operados y/o controlados por terceros. La inclusión en la Plataforma de vínculos a sitios de terceros cumple un fin meramente informativo, respecto de Inversionistas que quisieran obtener información adicional al momento de utilizar los servicios en la Plataforma. En consecuencia, Eollice no es responsable de la veracidad y autenticidad de la información proporcionada en estos sitios de terceros, accesibles desde hipervínculos existentes en la plataforma, ni tampoco se puede desprender y/o interpretar que por el hecho de encontrarse estos hipervínculos en las páginas de Plataforma, Eollice se encuentra recomendando dichos sitios, sus contenidos y/o servicios ofrecidos en los mismos.
En razón de lo anterior, el Inversionista comprende y acepta que: a) estos sitios de terceros no tienen relación legal con Eollice, quien no se responsabiliza por los contenidos e información de dichos sitios, por los servicios que ahí pudieran ofrecerse ni de la disponibilidad de los contenidos de los mismos; y b) los sitios de terceros se encuentran regidos por sus propias condiciones de uso, que no tienen relación con el presente Convenio de Uso de Plataforma. De esta forma, el Inversionista reconoce y declara que accede y utiliza dichos sitios web por su propia cuenta y riesgo.
</p><p><b>Omisión de responsabilidad</b><br>
El Inversionista reconoce y declara que su acceso a la Plataforma lo efectúa por su propia cuenta y riesgo, y que en consecuencia, y sin que la siguiente enumeración sea limitativa o exclusiva de otras hipótesis, Eollice no se responsabiliza por:
<ol>
  <li>Errores, omisiones, inexactitudes y/o falsedades en contenidos publicados por sus Inversionistas Registrados y Miembros en los Perfiles de Inversionistas.</li>
  <li>Cualquier daño o perjuicio al Inversionista causado por fallas en la Plataforma, software de Eollice y/o en sus sistemas;</li>
  <li>Cualquier virus que pudiera infectar el equipo del Inversionista producto del acceso y/o utilización de la Plataforma por parte del Inversionista, por tanto, el Inversionista comprende que el uso de este Sitio está sujeto al propio riesgo del Inversionista. Producto de lo anterior, si el uso de Plataforma deriva en que el Inversionista deba incurrir en reparaciones y/o correcciones, contratando algún servicio de mantención de sus equipos computacionales, estos costos deberán ser asumidos por el Inversionista, sin tener Eollice responsabilidad alguna en esta materia. Eollice se excluye de cualquier responsabilidad por los daños y perjuicios de cualquier naturaleza que puedan derivarse a la presencia de virus u otros elementos informáticos que pudieran producir alteraciones en los sistemas, documentos electrónicos y/o cuentas y perfiles de los Inversionistas</li>
  <li>No disponibilidad y continuidad de Plataforma. Eollice declara que el sistema puede eventualmente no encontrarse disponible debido a dificultades técnicas, fallas de internet o razones ajenas a Eollice, por lo que el Inversionista comprende que Eollice no garantiza el acceso continuo e ininterrumpido de Plataforma y/o de secciones del mismo. En caso de interrupción del servicio, Eollice hará su mejor esfuerzo por restablecer la Plataforma y sus servicios con prontitud, sin que de ello pudiera derivarse ningún tipo de obligación ni responsabilidad para Eollice. Eollice se excluye de cualquier responsabilidad por los daños y perjuicios de cualquier naturaleza que puedan derivarse a la falta de disponibilidad y continuidad del funcionamiento de la Plataforma y de los servicios.</li>
  <li>El monitoreo permanente o eventual de Plataforma, de los contenidos e información posteados por los Inversionistas, de los mensajes internos que envían, entre otras acciones que realicen los Inversionistas y que queden registradas y guardadas en la plataforma. Sin embargo, el Inversionista comprende y acepta que Eollice tiene el derecho de monitorear la Plataforma de manera electrónica, de tiempo en tiempo, y hacer seguimiento a cualquier información y/o conductas sospechosas de Inversionistas, según el propio criterio de Eollice y al servicio y satisfacción de la ley, regulaciones y/o requerimientos gubernamentales o de fiscalización, para asegurar la correcta operación de Plataforma y para protegerse a sí mismo y a otros Inversionistas de Plataforma, respecto de conductas que podrían ser fraudulentas y/o atentatorias contra los derechos de los Inversionistas.</li>
  <li>Conductas fraudulentas, de acoso, denigratorias, difamatorias, discriminatorias, amenazantes, inmorales, obscenas, pornográficas u ofensivas en que incurran Inversionistas y/o Miembros de Plataforma.</li>
  <li>Infracciones a leyes de propiedad intelectual incurridas por inversionistas de Plataforma, que hayan publicado o transmitido material de terceros que se encuentran resguardados por dichas leyes.</li>
  <li>Suplantación de identidad, es decir, que inversionistas utilicen datos personales de terceros para crear cuentas en Eollice. Sin embargo, Eollice se reserva el derecho de verificar las cuentas de manera aleatoria, verificando la veracidad de la información. En caso de detectar fraude, Eollice podrá cancelar la cuenta y entregar los antecedentes a la justicia chilena, especialmente en casos en que se haya producido un real daño o que denote intención de daño a terceros.</li>
  <li>Los resultados que se obtengan a partir del uso que el Inversionista haga de los servicios ofrecidos en la Plataforma.</li>
  <li>Cualquier infracción a este Convenio que realicen los Inversionistas de Plataforma o cualquier incumplimiento por parte de los Inversionistas de Eollice de las obligaciones y prohibiciones estipuladas en este acuerdo.</li>
</ol>
Bajo ninguna circunstancia los colaboradores, directores y los representantes de Eollice serán responsables por cualquier daño generado a los Inversionistas a partir del uso de Plataforma y de sus Contenidos. Los colaboradores, directores y representantes de Eollice no serán responsables de los daños generados por errores, omisiones, interrupciones, defectos, retrasos en la información, transmisión, virus computacionales, fallas de sistemas y otros problemas que se produzcan en el Sitio y en sus Contenidos.
Respecto de los casos enumerados previamente, el Inversionista no podrá imputarle responsabilidad legal alguna a Eollice ni exigir indemnizaciones ni pagos por daño emergente y/o lucro cesante, en virtud de perjuicios.
</p><p><b>Ley aplicable y tribunal competente</b><br>
El presente Convenio de Uso de Plataforma se encuentra sujeto y regido por las leyes vigentes en la República de Chile.
Cualquier conflicto o controversia surgida en relación con y/o a partir del presente Convenio de Uso de Plataforma, y/o sus Acuerdos Específicos, será sometida al conocimiento de los Tribunales competentes de la ciudad de Santiago de Chile. Para estos efectos, y en caso de ser procedente, se entiende que tanto el Inversionista como Eollice, renuncian en este acto y expresamente a cualquier otro fuero, sometiéndose a los Juzgados y Tribunales de la ciudad de Santiago.
Todos los procedimientos legales surgidos a partir de los conflictos o controversias se llevarán a cabo en idioma castellano.
El Inversionista acepta notificar a Eollice de manera escrita ante cualquier reclamo o disputa concerniente o relativa a este Sitio y a los Contenidos y servicios provistos en el mismo, y dar a Eollice un período razonable para responder al Inversionista, antes de comenzar cualquier acción legal contra Eollice.
</p><p><b>Adhesión del Convenio de uso de Plataforma</b><br>
Mediante la pulsión del botón “Acepto” ubicado al final del presente Convenio, el Inversionista o Inversionista reconoce y declara haber leído, comprendido y aceptado íntegramente el texto del Convenio de Uso de Plataforma en todas sus partes, aceptando ser regido por todos sus términos y condiciones, y estando sujeto a las leyes y regulaciones aplicables. Una vez pulsado el botón “Acepto” este Convenio será vinculante y obligará a las partes. Si el Inversionista no acepta el presente Convenio de Uso de Plataforma, deberá abstenerse de acceder, navegar y usar la Plataforma inmediatamente. Asimismo, no podrá hacer uso de sus servicios ni de la información disponible en las páginas web que lo conforman.
</p><p><b>Derecho de Eollice en relación con los contenidos de la Plataforma.</b><br>
Eollice podrá hacer cambios en los Contenidos y en la Plataforma, en cualquier momento y sin previa notificación a los Inversionistas. Asimismo, se deja constancia que la Plataforma podría contener errores técnicos y/o tipográficos y que Eollice no será responsable de cualquier perjuicio derivado de dichos errores involuntarios.
En caso que el Inversionista acepte dichas condiciones específicas, las mismas resultarán vinculantes para el Inversionista y se entenderán ser adicionales a los términos y condiciones de este Convenio de Uso de Plataforma, y pudiendo, según los casos, sustituir, completar y/o modificar el presente instrumento.
En el caso que – requerido al efecto – el Inversionista no acepte los términos y condiciones propuestos en los Acuerdos Específicos, Eollice se encontrará plenamente facultado para denegar a dicho Inversionista el acceso a las secciones específicas relevantes de Plataforma y de las páginas web que lo conforman. A este respecto, se deja expresa constancia de que Eollice podrá cambiar y/o restringir el acceso a todo o a una porción de Plataforma sin previa notificación al Inversionista y sin responsabilidad alguna para Eollice en caso que el Inversionista estime que se le haya generado un daño a partir de esa acción.
</p><p><b>Potestad de las clausulas.</b><br>
Si cualquier cláusula de este Convenio de Uso de Plataforma fuese declarada como inexistente, inválida, inoponible y/o de cualquier modo ineficaz por tribunal competente, las demás las cláusulas de este Convenio de Uso de Plataforma y los derechos y obligaciones que de ellas emanan, mantendrán su plena vigencia y validez.
Reformas y finalización del Convenio de uso de Plataforma.
</p><p><b>Reformas.</b><br> 
Eollice podrá en cualquier momento y de tiempo en tiempo, corregir, modificar, agregar, eliminar y actualizar los términos y condiciones de este Convenio de Uso de Plataforma, previa aceptación prestada al efecto por el Inversionista.
Para dichos efectos, Eollice notificará oportunamente al Inversionista de las modificaciones que se desee efectuar al Convenio de Uso de Plataforma a través de la publicación de una notificación dirigida al Inversionista cuando este intente acceder al Sitio. Los cambios en el Convenio de Uso de Plataforma se harán efectivos a partir del momento en que el Inversionista acepte las referidas modificaciones.
Lo anterior es sin perjuicio de la facultad de Eollice de condicionar el acceso a ciertas secciones específicas de Plataforma.
</p><p><b>Finalización del Convenio de uso de Plataforma</b><br>
Este Convenio de Uso de Plataforma se encontrará vigente y será efectivo mientras Eollice mantenga en operación la Plataforma. Eollice se reserva el derecho de terminar de ofrecer la Plataforma, sus contenidos y los servicios que se proveen a través de Plataforma en cualquier momento previa notificación a los Inversionistas de Eollice.
Sin perjuicio de lo anterior, Eollice podrá poner término inmediato al Convenio de Uso de Plataforma en caso de decidir, a su sola discreción, desactivar la cuenta de un Miembro y el Registro de Inversionista respectivo, en cualquiera de los siguientes casos:
<ol>  
  <li>En caso de comprobar que alguna de las informaciones suministradas por el Inversionista fuese falsa, incompleta, inexacta, errónea, y/o de cualquier forma poco fidedigna;</li>
  <li>En el evento de incurrir el Inversionista en un uso no autorizado del Contenido de Plataforma.</li>
  <li>En el evento de incurrir el Inversionista en alguna conducta u omisión que vulnere las disposiciones antispam,</li>
  <li>En el evento de incurrir el Inversionista en alguna infracción grave de sus obligaciones bajo el Convenio de Uso de Plataforma y/o los Acuerdos Específicos.</li>
</ol>
En tales casos, se entenderá que el Convenio de Uso de Plataforma y el Registro de Inversionista han expirado desde el momento en que Eollice así lo notifique al Inversionista mediante correo electrónico dirigido a la dirección registrada por éste con Eollice.
Sin embargo, las cláusulas que tratan sobre las siguientes materias, subsistirán y se mantendrán vigentes aun después del término del Convenio de Uso de Plataforma: 
Indemnizaciones, 
<ul>
  <li>Declaraciones y Garantías del Inversionista,</li>
  <li>Responsabilidades y Exclusiones,</li>
  <li>Ley Aplicable y Tribunal competente,</li>
  <li>y, en general cualquier otra materia que por su naturaleza perdure a pesar del término de este Convenio.</li>
</ul>
Se deja expresa constancia que el Inversionista no podrá retractarse del presente Convenio de Uso de Plataforma y sus anexos, de conformidad con lo dispuesto en la letra b) del artículo 3 bis de la Ley de Protección al Consumidor.
</p><br><p><b>4. Comunicación y notificaciones con los Inversionistas</b></p>
<p><b>Comunicación</b><br>
Al registrarse como inversionista, usted recibirá correos electrónicos que confirman acciones específicas requeridas. Usted recibirá notificaciones de confirmación de su registro, la verificación exitosa de direcciones de correo electrónico y cuentas bancarias, y la confirmación de compra de opciones de inversión. También podemos enviar respuestas a los correos electrónicos que nos envíe, en su caso. De vez en cuando, también vamos a enviar encuestas a los inversionistas, las solicitudes de comentarios de los inversionistas con respecto a la experiencia del inversionista y las operaciones de la Plataforma y las ofertas publicitarias de nosotros o de nosotros en nombre de nuestros socios de marketing. La realización de estas encuestas o solicitudes de información o la aceptación de cualquier oferta es estrictamente voluntaria. Si no desea recibir estas ofertas, encuestas o e-mail de inversionista, por favor optar en cualquier oferta de correo electrónico que reciba de nosotros.
</p><p><b>Notificaciones</b><br>
Recibirá notificaciones por correo electrónico de vez en cuando. Dichas notificaciones se requieren elementos de sus transacciones en nuestra plataforma, tales como confirmaciones de acciones particulares que ha tomado. Estas notificaciones requeridas se envían normalmente para notificarle de un cambio de estado, como cuando se confirma como un inversionista, o con fines legales o de seguridad. Por ejemplo, algunas notificaciones se envían para su propia protección para garantizar que otra persona no puede hacer un cambio en su cuenta sin su conocimiento. En otros casos, estas notificaciones implican cambios en los diversos acuerdos legales o políticas de la Plataforma. En general, usted no puede optar por estos mensajes de correo electrónico relacionados con el servicio.
Las comunicaciones que el Inversionista deba o quiera dirigir a Eollice, se efectuarán por correo electrónico dirigido a contacto@Eollice.com, o bien a través de la sección Contacto de www.Eollice.com.
Las comunicaciones que Eollice deba o quiera dirigir al Inversionista, se efectuarán por correo electrónico dirigido a la dirección electrónica designada por el Inversionista en el Proceso de Registro.
</p><p><b>Declaración</b><br>
En este acto y por el presente, el Inversionista reconoce haber leído por vía electrónica, y comprendido, el contenido íntegro del Convenio de Uso de Plataforma, y que al presionar el botón de “Acepto” incluido abajo, acepta expresa, inequívoca e irrevocablemente el Convenio de Uso de Plataforma. El documento electrónico en que se formalice el presente Convenio será archivado en la base de datos de Eollice, y será accesible al Inversionista en su Perfil de Inversionista. En caso que el Inversionista necesite identificar y corregir errores en el envío o en sus datos, podrá contactar a Eollice por los medios indicados en la cláusula décimo tercera del presente instrumento. Se deja constancia que verificada la aceptación del presente Convenio en los términos antes referidos, Eollice enviará una confirmación del perfeccionamiento del Convenio de Uso de Plataforma al Inversionista por correo electrónico, conteniendo una copia íntegra, clara y legible del Convenio.
</p>
        </div>
        <div class="modal-footer">
          <button type="button" id="acept_terms_btn" disabled="disabled" class="btn btn-primary">Aceptar</button>
          <button type="button" class="btn btn-default" data-dismiss="modal" id="reject_terms_btn">Rechazar</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->